In [43]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [8]:
dataset=load_wine()
columns=['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids',
         'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
data=dataset.data

#normalisation/feature scaling
mean=data.mean()
std=data.std()
data=(data-mean)/std

In [9]:
df=pd.DataFrame(data,columns=columns)
y=dataset.target

In [11]:
x_train, x_test, y_train, y_test = train_test_split(df, y, test_size=0.3,random_state=0)

In [37]:
lr=LogisticRegression(solver='saga',max_iter=500,multi_class='multinomial')
lr.fit(x_train,y_train)
y_predict=lr.predict(x_test)

cm=confusion_matrix(y_test,y_predict)
print(cm)
print("ACCURACY :",((cm[0][0]+cm[1][1]+cm[2][2])/np.sum(cm)) )

[[17  0  2]
 [ 1 19  2]
 [ 1  6  6]]
ACCURACY : 0.7777777777777778


In [40]:
#using descision tree
dtc= DecisionTreeClassifier()
dtc.fit(x_train, y_train)
y_predict=dtc.predict(x_test)

cm=confusion_matrix(y_test,y_predict)
print(cm)
print("ACCURACY :",((cm[0][0]+cm[1][1]+cm[2][2])/np.sum(cm)) )


[[18  1  0]
 [ 1 20  1]
 [ 0  0 13]]
ACCURACY : 0.9444444444444444


In [46]:
svm = SVC(gamma='auto')
svm.fit(x_train, y_train)
y_predict=svm.predict(x_test)

cm=confusion_matrix(y_test,y_predict)
print(cm)
print("ACCURACY :",((cm[0][0]+cm[1][1]+cm[2][2])/np.sum(cm)) )

[[17  0  2]
 [ 1 21  0]
 [ 1  7  5]]
ACCURACY : 0.7962962962962963


In [45]:
gnb = GaussianNB()
gnb.fit(x_train, y_train)
y_predict=gnb.predict(x_test)

cm=confusion_matrix(y_test,y_predict)
print(cm)
print("ACCURACY :",((cm[0][0]+cm[1][1]+cm[2][2])/np.sum(cm)) )

[[19  0  0]
 [ 2 19  1]
 [ 0  0 13]]
ACCURACY : 0.9444444444444444
